### ISSUE TITLE
deprecated for?

### ISSUE THREAD

**Issue by u9520107** [jspm/nodelibs#5]
@guybedford A bit confused here. Is this lib being deprecated in favor of separate modules like the nodelibs-fs modules? Don't want to include something in our framework if it would disappear in the end.

**Comment by guybedford** [comment]
This has been deprecated for the individual repos like https://github.com/jspm/nodelibs-fs. You can install these with `jspm install fs`.

**Comment by u9520107** [comment]
Ic.. This is great actually. Thanks!
